services:
    twig.extension.approximate_date:
        class: Metalslave\ApproximateDateBundle\Twig\Extension\ApproximateDateExtension
        arguments:
            - "@sonata.intl.twig.extension.datetime"
            - "@translator"
        tags:
            - { name: twig.extension}
